from __future__ import annotations

from sqlalchemy import Boolean, Column, DateTime, Float, ForeignKey, ForeignKeyConstraint, Index, Integer, MetaData, Table, Text, text
from sqlalchemy.dialects.postgresql import JSONB, UUID
from sqlalchemy.sql import func

metadata = MetaData()

projects = Table(
    "projects",
    metadata,
    Column("project_id", Text, primary_key=True),
    Column("name", Text, nullable=False),
    Column("status", Text, nullable=True),
    Column("source", Text, nullable=True),
    Column("updated_at", DateTime(timezone=True), nullable=True),
    Column("created_at", DateTime(timezone=True), nullable=False, server_default=func.now()),
    Column("raw", JSONB, nullable=True),
    Index("ix_projects_name", "name"),
    Index("ix_projects_status", "status"),
)

tasks = Table(
    "tasks",
    metadata,
    Column("task_id", Text, primary_key=True),
    Column("title", Text, nullable=False),
    Column("status", Text, nullable=True),
    Column("priority", Text, nullable=True),
    Column("due", Text, nullable=True),
    Column("project_id", Text, nullable=True),
    Column("source", Text, nullable=True),
    Column("updated_at", DateTime(timezone=True), nullable=True),
    Column("created_at", DateTime(timezone=True), nullable=False, server_default=func.now()),
    Column("raw", JSONB, nullable=True),
    Index("ix_tasks_title", "title"),
    Index("ix_tasks_status", "status"),
    Index("ix_tasks_project_id", "project_id"),
)

intel_articles = Table(
    "intel_articles",
    metadata,
    Column("article_id", Text, primary_key=True),
    Column("url_original", Text, nullable=True),
    Column("url", Text, nullable=False),
    Column("title", Text, nullable=False),
    Column("publisher", Text, nullable=True),
    Column("author", Text, nullable=True),
    Column("published_at", DateTime(timezone=True), nullable=True),
    Column("ingested_at", DateTime(timezone=True), nullable=False, server_default=func.now()),
    Column("topics", JSONB, nullable=False, server_default=text("'[]'::jsonb")),
    Column("summary", Text, nullable=False, server_default=text("''")),
    Column("signals", JSONB, nullable=False, server_default=text("'[]'::jsonb")),
    Column("outline", JSONB, nullable=False, server_default=text("'[]'::jsonb")),
    Column("outbound_links", JSONB, nullable=False, server_default=text("'[]'::jsonb")),
    Column("raw_html", Text, nullable=True),
    Column("extracted_text", Text, nullable=True),
    Column("http_status", Integer, nullable=True),
    Column("content_type", Text, nullable=True),
    Column("etag", Text, nullable=True),
    Column("last_modified", Text, nullable=True),
    Column("fetch_meta", JSONB, nullable=True),
    Column("extraction_meta", JSONB, nullable=True),
    Column("enrichment_meta", JSONB, nullable=True),
    Column("status", Text, nullable=False, server_default=text("'queued'")),
    Column("updated_at", DateTime(timezone=True), nullable=False, server_default=func.now()),
    Column("tags", JSONB, nullable=False, server_default=text("'[]'::jsonb")),
    Index("ix_intel_articles_ingested_at", "ingested_at"),
    Index("ix_intel_articles_published_at", "published_at"),
)

intel_article_sections = Table(
    "intel_article_sections",
    metadata,
    Column(
        "article_id",
        Text,
        ForeignKey("intel_articles.article_id", ondelete="CASCADE"),
        primary_key=True,
    ),
    Column("section_id", Text, primary_key=True),
    Column("heading", Text, nullable=False, server_default=text("''")),
    Column("content", Text, nullable=False),
    Column("rank", Integer, nullable=False, server_default=text("0")),
)

intel_ingest_jobs = Table(
    "intel_ingest_jobs",
    metadata,
    Column("job_id", UUID(as_uuid=True), primary_key=True),
    Column("url_original", Text, nullable=False),
    Column("url_canonical", Text, nullable=False),
    Column("article_id", Text, nullable=False),
    Column("status", Text, nullable=False, server_default=text("'queued'")),
    Column("attempts", Integer, nullable=False, server_default=text("0")),
    Column("last_error", Text, nullable=True),
    Column("created_at", DateTime(timezone=True), nullable=False, server_default=func.now()),
    Column("updated_at", DateTime(timezone=True), nullable=False, server_default=func.now()),
    Index("ix_intel_ingest_jobs_status_created_at", "status", "created_at"),
    Index("ix_intel_ingest_jobs_article_id", "article_id"),
)

research_sources = Table(
    "research_sources",
    metadata,
    Column("source_id", Text, primary_key=True),
    Column("topic_key", Text, nullable=False),
    Column("kind", Text, nullable=False),
    Column("name", Text, nullable=False),
    Column("base_url_original", Text, nullable=False),
    Column("base_url_canonical", Text, nullable=False),
    Column("enabled", Boolean, nullable=False, server_default=text("true")),
    Column("tags", JSONB, nullable=False, server_default=text("'[]'::jsonb")),
    Column("publisher_type", Text, nullable=False, server_default=text("'independent'")),
    Column("source_class", Text, nullable=False, server_default=text("'external_commentary'")),
    Column("default_decision_domains", JSONB, nullable=False, server_default=text("'[]'::jsonb")),
    Column("created_at", DateTime(timezone=True), nullable=False, server_default=func.now()),
    Column("updated_at", DateTime(timezone=True), nullable=False, server_default=func.now()),
    Index("ix_research_sources_topic_key", "topic_key"),
    Index("ix_research_sources_enabled", "enabled"),
    Index("uq_research_sources_topic_kind_canonical", "topic_key", "kind", "base_url_canonical", unique=True),
)

research_source_policies = Table(
    "research_source_policies",
    metadata,
    Column("source_id", Text, ForeignKey("research_sources.source_id", ondelete="CASCADE"), primary_key=True),
    Column("poll_interval_minutes", Integer, nullable=False, server_default=text("60")),
    Column("rate_limit_per_hour", Integer, nullable=False, server_default=text("30")),
    Column("robots_mode", Text, nullable=False, server_default=text("'strict'")),
    Column("max_items_per_run", Integer, nullable=False, server_default=text("50")),
    Column("source_weight", Float, nullable=False, server_default=text("1.0")),
    Column("last_polled_at", DateTime(timezone=True), nullable=True),
    Column("consecutive_failures", Integer, nullable=False, server_default=text("0")),
    Column("cooldown_until", DateTime(timezone=True), nullable=True),
    Column("last_error", Text, nullable=True),
    Column("updated_at", DateTime(timezone=True), nullable=False, server_default=func.now()),
    Index("ix_research_source_policies_cooldown_until", "cooldown_until"),
)

research_ingestion_runs = Table(
    "research_ingestion_runs",
    metadata,
    Column("run_id", UUID(as_uuid=True), primary_key=True),
    Column("topic_key", Text, nullable=False),
    Column("trigger", Text, nullable=False),
    Column("status", Text, nullable=False, server_default=text("'queued'")),
    Column("idempotency_key", Text, nullable=True),
    Column("requested_source_ids", JSONB, nullable=False, server_default=text("'[]'::jsonb")),
    Column("selected_source_ids", JSONB, nullable=False, server_default=text("'[]'::jsonb")),
    Column("items_seen", Integer, nullable=False, server_default=text("0")),
    Column("items_new", Integer, nullable=False, server_default=text("0")),
    Column("items_deduped", Integer, nullable=False, server_default=text("0")),
    Column("items_failed", Integer, nullable=False, server_default=text("0")),
    Column("errors", JSONB, nullable=False, server_default=text("'[]'::jsonb")),
    Column("created_at", DateTime(timezone=True), nullable=False, server_default=func.now()),
    Column("started_at", DateTime(timezone=True), nullable=True),
    Column("finished_at", DateTime(timezone=True), nullable=True),
    Column("updated_at", DateTime(timezone=True), nullable=False, server_default=func.now()),
    Index("ix_research_runs_status_created_at", "status", "created_at"),
    Index("ix_research_runs_topic_key", "topic_key"),
    Index("ix_research_runs_idempotency_key", "idempotency_key"),
)

research_documents = Table(
    "research_documents",
    metadata,
    Column("document_id", Text, primary_key=True),
    Column("source_id", Text, ForeignKey("research_sources.source_id", ondelete="CASCADE"), nullable=False),
    Column("run_id", UUID(as_uuid=True), ForeignKey("research_ingestion_runs.run_id", ondelete="SET NULL"), nullable=True),
    Column("canonical_url", Text, nullable=False),
    Column("url_original", Text, nullable=True),
    Column("external_id", Text, nullable=True),
    Column("title", Text, nullable=True),
    Column("published_at", DateTime(timezone=True), nullable=True),
    Column("published_at_confidence", Float, nullable=False, server_default=text("0.0")),
    Column("status", Text, nullable=False, server_default=text("'discovered'")),
    Column("raw_payload", Text, nullable=True),
    Column("extracted_text", Text, nullable=True),
    Column("content_hash", Text, nullable=True),
    Column("content_type", Text, nullable=False, server_default=text("'company_blog'")),
    Column("publisher_type", Text, nullable=False, server_default=text("'independent'")),
    Column("source_class", Text, nullable=False, server_default=text("'external_commentary'")),
    Column("summary_short", Text, nullable=False, server_default=text("''")),
    Column("why_it_matters", Text, nullable=False, server_default=text("''")),
    Column("topic_tags", JSONB, nullable=False, server_default=text("'[]'::jsonb")),
    Column("entity_tags", JSONB, nullable=False, server_default=text("'[]'::jsonb")),
    Column("use_case_tags", JSONB, nullable=False, server_default=text("'[]'::jsonb")),
    Column("decision_domains", JSONB, nullable=False, server_default=text("'[]'::jsonb")),
    Column("quality_signals", JSONB, nullable=False, server_default=text("'{}'::jsonb")),
    Column("metrics", JSONB, nullable=False, server_default=text("'[]'::jsonb")),
    Column("notable_quotes", JSONB, nullable=False, server_default=text("'[]'::jsonb")),
    Column("key_claims", JSONB, nullable=False, server_default=text("'[]'::jsonb")),
    Column("tradeoffs", JSONB, nullable=False, server_default=text("'[]'::jsonb")),
    Column("recommendations", JSONB, nullable=False, server_default=text("'[]'::jsonb")),
    Column("novelty_score", Float, nullable=False, server_default=text("0.0")),
    Column("evidence_density_score", Float, nullable=False, server_default=text("0.0")),
    Column("document_signal_score", Float, nullable=False, server_default=text("0.0")),
    Column("embedding_ready", Boolean, nullable=False, server_default=text("false")),
    Column("fetch_meta", JSONB, nullable=True),
    Column("extraction_meta", JSONB, nullable=True),
    Column("enrichment_meta", JSONB, nullable=True),
    Column("created_at", DateTime(timezone=True), nullable=False, server_default=func.now()),
    Column("discovered_at", DateTime(timezone=True), nullable=False, server_default=func.now()),
    Column("fetched_at", DateTime(timezone=True), nullable=True),
    Column("extracted_at", DateTime(timezone=True), nullable=True),
    Column("embedding_model_id", Text, nullable=True),
    Column("embedded_at", DateTime(timezone=True), nullable=True),
    Column("updated_at", DateTime(timezone=True), nullable=False, server_default=func.now()),
    Index("ix_research_documents_source_id", "source_id"),
    Index("ix_research_documents_status", "status"),
    Index("ix_research_documents_canonical_url", "canonical_url"),
)

research_chunks = Table(
    "research_chunks",
    metadata,
    Column("document_id", Text, ForeignKey("research_documents.document_id", ondelete="CASCADE"), primary_key=True),
    Column("chunk_id", Text, primary_key=True),
    Column("ordinal", Integer, nullable=False),
    Column("content", Text, nullable=False),
    Column("content_hash", Text, nullable=False),
    Column("chunk_meta", JSONB, nullable=False, server_default=text("'{}'::jsonb")),
    Column("created_at", DateTime(timezone=True), nullable=False, server_default=func.now()),
    Index("ix_research_chunks_document_id", "document_id"),
    Index("ix_research_chunks_ordinal", "ordinal"),
)

research_embeddings = Table(
    "research_embeddings",
    metadata,
    Column("document_id", Text, nullable=False, primary_key=True),
    Column("chunk_id", Text, nullable=False, primary_key=True),
    Column("embedding_model_id", Text, nullable=False, primary_key=True),
    Column("vector", JSONB, nullable=False),
    Column("created_at", DateTime(timezone=True), nullable=False, server_default=func.now()),
    Column("updated_at", DateTime(timezone=True), nullable=False, server_default=func.now()),
    ForeignKeyConstraint(
        ["document_id", "chunk_id"],
        ["research_chunks.document_id", "research_chunks.chunk_id"],
        ondelete="CASCADE",
    ),
    Index("ix_research_embeddings_document_model", "document_id", "embedding_model_id"),
)

research_query_logs = Table(
    "research_query_logs",
    metadata,
    Column("query_log_id", UUID(as_uuid=True), primary_key=True),
    Column("trace_id", Text, nullable=False),
    Column("topic_key", Text, nullable=False),
    Column("query_text", Text, nullable=False),
    Column("source_ids", JSONB, nullable=False, server_default=text("'[]'::jsonb")),
    Column("token_budget", Integer, nullable=True),
    Column("max_items", Integer, nullable=True),
    Column("recency_days", Integer, nullable=True),
    Column("min_relevance_score", Float, nullable=True),
    Column("candidate_count", Integer, nullable=False, server_default=text("0")),
    Column("returned_document_ids", JSONB, nullable=False, server_default=text("'[]'::jsonb")),
    Column("returned_chunk_ids", JSONB, nullable=False, server_default=text("'[]'::jsonb")),
    Column("timing_ms", Integer, nullable=False, server_default=text("0")),
    Column("status", Text, nullable=False, server_default=text("'ok'")),
    Column("error", Text, nullable=True),
    Column("created_at", DateTime(timezone=True), nullable=False, server_default=func.now()),
    Index("ix_research_query_logs_topic_created_at", "topic_key", "created_at"),
    Index("ix_research_query_logs_trace_id", "trace_id", unique=True),
)

research_relevance_scores = Table(
    "research_relevance_scores",
    metadata,
    Column("score_id", UUID(as_uuid=True), primary_key=True),
    Column("trace_id", Text, nullable=False),
    Column("topic_key", Text, nullable=False),
    Column("query_text", Text, nullable=False),
    Column("document_id", Text, ForeignKey("research_documents.document_id", ondelete="CASCADE"), nullable=False),
    Column("chunk_id", Text, nullable=False),
    Column("score_total", Float, nullable=False),
    Column("score_lexical", Float, nullable=False),
    Column("score_embedding", Float, nullable=False),
    Column("score_recency", Float, nullable=False),
    Column("score_source_weight", Float, nullable=False),
    Column("created_at", DateTime(timezone=True), nullable=False, server_default=func.now()),
    Index("ix_research_relevance_scores_trace", "trace_id", "created_at"),
)

research_retrieval_feedback = Table(
    "research_retrieval_feedback",
    metadata,
    Column("feedback_id", UUID(as_uuid=True), primary_key=True),
    Column("trace_id", Text, nullable=False),
    Column("query_log_id", UUID(as_uuid=True), ForeignKey("research_query_logs.query_log_id", ondelete="SET NULL"), nullable=True),
    Column("document_id", Text, ForeignKey("research_documents.document_id", ondelete="CASCADE"), nullable=False),
    Column("chunk_id", Text, nullable=False),
    Column("verdict", Text, nullable=False),
    Column("notes", Text, nullable=True),
    Column("created_at", DateTime(timezone=True), nullable=False, server_default=func.now()),
    Index("ix_research_retrieval_feedback_trace", "trace_id", "created_at"),
)

research_bootstrap_events = Table(
    "research_bootstrap_events",
    metadata,
    Column("event_id", UUID(as_uuid=True), primary_key=True),
    Column("topic_key", Text, nullable=False),
    Column("idempotency_key", Text, nullable=True),
    Column("request_hash", Text, nullable=False),
    Column("received", Integer, nullable=False, server_default=text("0")),
    Column("valid", Integer, nullable=False, server_default=text("0")),
    Column("invalid", Integer, nullable=False, server_default=text("0")),
    Column("created", Integer, nullable=False, server_default=text("0")),
    Column("updated", Integer, nullable=False, server_default=text("0")),
    Column("skipped_duplicate", Integer, nullable=False, server_default=text("0")),
    Column("results", JSONB, nullable=False, server_default=text("'[]'::jsonb")),
    Column("run_id", UUID(as_uuid=True), ForeignKey("research_ingestion_runs.run_id", ondelete="SET NULL"), nullable=True),
    Column("created_at", DateTime(timezone=True), nullable=False, server_default=func.now()),
    Index("ix_research_bootstrap_events_topic_created_at", "topic_key", "created_at"),
    Index("ix_research_bootstrap_events_idempotency_key", "idempotency_key"),
)

research_document_insights = Table(
    "research_document_insights",
    metadata,
    Column("insight_id", UUID(as_uuid=True), primary_key=True),
    Column("document_id", Text, ForeignKey("research_documents.document_id", ondelete="CASCADE"), nullable=False),
    Column("chunk_id", Text, nullable=False),
    Column("insight_type", Text, nullable=False),
    Column("text", Text, nullable=False),
    Column("normalized_payload", JSONB, nullable=False, server_default=text("'{}'::jsonb")),
    Column("topic_tags", JSONB, nullable=False, server_default=text("'[]'::jsonb")),
    Column("entity_tags", JSONB, nullable=False, server_default=text("'[]'::jsonb")),
    Column("problem_tags", JSONB, nullable=False, server_default=text("'[]'::jsonb")),
    Column("intervention_tags", JSONB, nullable=False, server_default=text("'[]'::jsonb")),
    Column("tradeoff_dimensions", JSONB, nullable=False, server_default=text("'[]'::jsonb")),
    Column("decision_domains", JSONB, nullable=False, server_default=text("'[]'::jsonb")),
    Column("source_class", Text, nullable=False, server_default=text("'external_commentary'")),
    Column("publisher_type", Text, nullable=False, server_default=text("'independent'")),
    Column("confidence", Float, nullable=False, server_default=text("0.0")),
    Column("evidence_strength", Float, nullable=False, server_default=text("0.0")),
    Column("freshness_score", Float, nullable=False, server_default=text("0.0")),
    Column("applicability_conditions", JSONB, nullable=False, server_default=text("'[]'::jsonb")),
    Column("source_trust_tier", Float, nullable=False, server_default=text("0.0")),
    Column("corroboration_count", Integer, nullable=False, server_default=text("0")),
    Column("contradiction_count", Integer, nullable=False, server_default=text("0")),
    Column("coverage_score", Float, nullable=False, server_default=text("0.0")),
    Column("internal_coverage_score", Float, nullable=False, server_default=text("0.0")),
    Column("external_coverage_score", Float, nullable=False, server_default=text("0.0")),
    Column("evidence_quality", Float, nullable=False, server_default=text("0.0")),
    Column("staleness_flag", Boolean, nullable=False, server_default=text("false")),
    Column("superseded_flag", Boolean, nullable=False, server_default=text("false")),
    Column("superseded_by_insight_id", UUID(as_uuid=True), nullable=True),
    Column("created_at", DateTime(timezone=True), nullable=False, server_default=func.now()),
    Index("ix_research_document_insights_document_type", "document_id", "insight_type"),
    Index("ix_research_document_insights_type", "insight_type"),
    Index("ix_research_document_insights_problem_tags", "problem_tags", postgresql_using="gin"),
    Index("ix_research_document_insights_intervention_tags", "intervention_tags", postgresql_using="gin"),
    Index("ix_research_document_insights_topic_tags", "topic_tags", postgresql_using="gin"),
)

research_evidence_relations = Table(
    "research_evidence_relations",
    metadata,
    Column("relation_id", UUID(as_uuid=True), primary_key=True),
    Column("from_insight_id", UUID(as_uuid=True), ForeignKey("research_document_insights.insight_id", ondelete="CASCADE"), nullable=False),
    Column("to_insight_id", UUID(as_uuid=True), ForeignKey("research_document_insights.insight_id", ondelete="CASCADE"), nullable=False),
    Column("relation_type", Text, nullable=False),
    Column("confidence", Float, nullable=False, server_default=text("0.0")),
    Column("explanation", Text, nullable=True),
    Column("created_at", DateTime(timezone=True), nullable=False, server_default=func.now()),
    Index("ix_research_evidence_relations_from", "from_insight_id", "relation_type"),
    Index("ix_research_evidence_relations_to", "to_insight_id", "relation_type"),
)

research_decision_feedback = Table(
    "research_decision_feedback",
    metadata,
    Column("feedback_id", UUID(as_uuid=True), primary_key=True),
    Column("trace_id", Text, nullable=False),
    Column("topic_key", Text, nullable=False),
    Column("decision_domain", Text, nullable=True),
    Column("verdict", Text, nullable=False),
    Column("followed_recommendation", Boolean, nullable=False, server_default=text("false")),
    Column("evidence_sufficient", Boolean, nullable=False, server_default=text("false")),
    Column("notes", Text, nullable=True),
    Column("created_at", DateTime(timezone=True), nullable=False, server_default=func.now()),
    Index("ix_research_decision_feedback_topic_created_at", "topic_key", "created_at"),
)

research_digest_feedback = Table(
    "research_digest_feedback",
    metadata,
    Column("feedback_id", UUID(as_uuid=True), primary_key=True),
    Column("topic_key", Text, nullable=False),
    Column("cluster_key", Text, nullable=False),
    Column("verdict", Text, nullable=False),
    Column("selected_for_publication", Boolean, nullable=False, server_default=text("false")),
    Column("quotes_usable", Boolean, nullable=False, server_default=text("false")),
    Column("metrics_usable", Boolean, nullable=False, server_default=text("false")),
    Column("notes", Text, nullable=True),
    Column("created_at", DateTime(timezone=True), nullable=False, server_default=func.now()),
    Index("ix_research_digest_feedback_topic_created_at", "topic_key", "created_at"),
)
